// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountModalController from "./account_modal_controller"
application.register("account-modal", AccountModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UserMenuController from "./user_menu_controller"
application.register("user-menu", UserMenuController)
