// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountModalController from "./account_modal_controller"
application.register("account-modal", AccountModalController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import DetailsModalController from "./details_modal_controller"
application.register("details-modal", DetailsModalController)

import FoodsModalController from "./foods_modal_controller"
application.register("foods-modal", FoodsModalController)

import FoodsSelectionController from "./foods_selection_controller"
application.register("foods-selection", FoodsSelectionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HowToModalController from "./how_to_modal_controller"
application.register("how-to-modal", HowToModalController)

import ReminderModalController from "./reminder_modal_controller"
application.register("reminder-modal", ReminderModalController)

import UserFoodModalController from "./user_food_modal_controller"
application.register("user-food-modal", UserFoodModalController)

import UserMenuController from "./user_menu_controller"
application.register("user-menu", UserMenuController)
